# This is a basic workflow to help you get started with Actions

name: GitHub Action Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 14
        architecture:
          - x64
          - arm64
    
    # List of services used for this workload
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: rootpw
        ports:
          - 3306:3306
    
    name: Node 14 - ${{ matrix.architecture }} on ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup MariaDB
      - name: Setup MariaDB test account
        run: |
          sudo apt update
          sudo apt install -y mysql-client
          mysql --host mariadb --username=root --password=rootpw -e "CREATE USER 'testdb'@'localhost'; GRANT ALL PRIVILEGES ON *.* to 'testdb'@'localhost';"

      # Install Node.JS
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      
      # Install Dependencies
      - name: Install Dependencies
        run: npm ci
      
      # Run Test
      - name: Run Test
        run: npm run test
